### ISSUE TITLE
Intake roadmap

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1]
These are plain-language descriptions of the steps that exist in the [4 main typeseam views](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/views.py#L24-L56).

Views
- [x] `/` Show a [splash page](https://clearmyrecord.codeforamerica.org/) at the root URL, with an "apply now" link
- [x] `/apply/` - The page with the form. Comparable to [`/sanfrancisco/`](https://clearmyrecord.codeforamerica.org/sanfrancisco/). This should display a form on a GET request, In Typeseam, this form is currently [written in html](https://github.com/codeforamerica/typeseam/blob/master/typeseam/templates/forms/sanfrancisco.html). Upon submission, the view should:
  - [x] store the submission information.
  - [x] [send a notification email](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/tasks.py#L55-L65) to `DEFAULT_NOTIFICATION_EMAIL` (an environmental variable) with a link to a pdf detail view for the given submission (see below)
  - [x] redirect to a `/thanks/` page
- [x] `/thanks/` - a page to thank people for finishing the form.
- [x] `/sanfrancisco/<uuid>/` - the submission detail view. login required.
  - [x] retrieve the submission based on the unique identifier in the url
  - [x] get the bytes of a filled pdf using the answers of this submission. Currently the pdf is in the source code. the pdf-filling functionality requires the [`pdfparser` module](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/pdfparser.py) and [`pdfparser.jar`](https://github.com/codeforamerica/typeseam/blob/master/pdfparser.jar). Filling a pdf is currently implemented as [a method](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/models.py#L106-L112) on the `Submission` model.  This includes [a translation step](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/models.py#L114-L121) that [builds a JSON](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/models.py#L49-L85) that fits the needs of the pdfparser's API.
  - [x] [send a notification email](https://github.com/codeforamerica/typeseam/blob/master/typeseam/form_filler/tasks.py#L68-L79) to `DEFAULT_NOTIFICATION_EMAIL` saying which logged in user accessed the detail view.

Models
- a `Submission` model that stores people's answers from the application form along with the date & time of submission.
- `User` - the default should work just fine for now. In the current application, users do not have an extra "username" field. They just use their email for login. I'd like to keep it this way if possible.

Additional aspects
- [x] ideally, user accounts should be invitation only.

**Comment by bengolder** [comment]
### Functional tests

##### Authentication & Accounts
- [ ] Can invite a new user
- [ ] Can add a new organization
- [ ] A new user can add their own information
- [ ] Users can login with just email and a password
- [ ] Users can logout
- [ ] Users can reset passwords
- [ ] Users can edit their name
- [ ] Users can edit their contact info
- [ ] Users can forget their password and get a link to reset it.
- [ ] Users get a decent error message for bad passwords or emails.

##### Core views
- [ ] unathenticated user can fill out an application form and get a thanks page
- [ ] Authenticated user can see the filled pdf
- [ ] Authenticated user can see the list of submitted applications
- [ ] Authenticated user from another organization or an unauthenticated user cannot see the list of apps of the filled pdf
- [ ] Authenticated user can delete applications
- [ ] Authenticated user can mark applications as "processed"

##### Notifications
- [ ] Org users get an email when their is a new application
