### ISSUE TITLE
Deploy Clips

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1074]
# Create Small Read Replica and Create Clips User

In moving our databases to RDS we deprecated the Heroku DataClips tool.  To replace this we have created a clips application in intake which allow a user to save, and run queries on a read replica using a user with read-only permissions on a limited schema. This ability is needed to generate periodic reports to CxO.

## Tasks

8/11 Afternoon
- [x] Create Read Replica thats a t2.small
  - [x] Remove larger Read Replica
- [x] Create roles and change permission on production with Ansible
  - Create Clips user
  - Give Clips access to Purged Schema
  - Give Intake user explicit create tables on public
  - Revoke global create and usage access on public
- [x] Check that Production isn't broken by newly set permissions causing 500-errors in production.
- [] if rollback needed here: Grant create, usage on public to public
- [x] Add PURGED_DATABASE_HST/PASSWORD/USER environment variables to cmr-prod
- [x] Create PR and confirm only the Clips changes are going out.  If not discuss.
- [x] Merged Develop branch onto master and deploy and update cmr-stage to pull off master

8/22 Morning
- [x] Promote cmr-stage to cmr-prod
- [x] Manually check that Clips works
- [ ] Give permissions to CfA staff so they can use it(co-ordinate with team)

Same day
- [x] Number queries should be consistent with past behaviour. Confirm number of connections double.
- [x] Confirm CfA user can access query data needs for CxO report.  If not which tables will help.

## Do you expect any changes to production metrics? Did you see any changes in staging?

Since the production already has a read replica adding a smaller read replica and removing the larger replica should only have minor temporary performance impact. Historically, when we create read replicas in the past, they have not had any noticeable impact to production.

## What metrics to closely monitor before+after?

Database queries should have no change in metrics on New Relic
Database connections should double(worth checking).
Scan logs for any stackdumps or 500 errors.

## Will this change the application development or deployment process?

There is currently a bug in Django which causes tests to behave erratically if two databases have the same name.  This is know limitation with 1.10 and meand means we can only have one local database while running tests.

## Will this require downtime or partial outage of service?

None planned

## Once deployed, is it possible to rollback if needed without losing data?

Yes.  If something goes wrong while deploying the code we can revert the release.  If something goes wrong when setting up new postgres users we can grant the revoked the permissions.

## What could possibly go wrong and what are the mitigations needed?

The main potential problem could be database corruption.  The best mitigation will be to backup the database to be able to quickly roll back.  Since this will not be in maintenance mode this would mean potential loss of data but the risk is very low.

## Based on whats being changed are there any manual UAT or tests that should be run on the system after the deployment?

- [x] Check Production isn't 500ing(low to no risk) after creating Clips user and after deploying code.
- [x] Query time and count should be consistent with past behaviour.  Confirm in New Relic
- [x] Confirm CfA user can access query data needs for CxO report.  If not which tables will help.

**Comment by joduinn** [comment]
@TiffanyAndrews @bengolder @loumoore here's a first pass at doing an Ops ticket (per postmortem last week). Can you have a look at this and see if anything missing?

**Comment by glassresistor** [comment]
Everything is deployed and @TiffanyAndrews has been added to the clips_user group
