### ISSUE TITLE
Policies for the S3 Sync Users have Improper Resource ARNs

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1117]
When creating the commands to sync the postgres databases I noticed that the two sync users were not able to access the sync bucket.

Looking at the IAM policies I see an error in the name.  I will need to update the user creation playbooks and recreate the users.  

Since this is changing roles on a live system it should be treated as an Ops ticket and follow the template in Infra.

**Comment by glassresistor** [comment]
# Updating Inline Policies for Production and Staging's sync Users

For staging and production to be able to sync it each needs to have a user that can read and write to the sync folder, which is used to hold a json representation of the production database.  The bucket names they were given access to need to be corrected so syncing can work.  The staging's sync user also needs full full permissions on the staging media bucket.

Since we will also be testing that syncing can happen from the production media bucket to the staging one we should turn on versioning as well as logging for the production media bucket.

## Do you expect any changes to production metrics? Did you see any changes in staging?

No

## What metrics to closely monitor before+after?

None

## Will this change the application development or deployment process?

No

## Will this require downtime or partial outage of service?

None is expected.

## Once deployed, is it possible to rollback if needed without losing data?

Yes because this is currently unused going forward or backward should not cause issues.

## What could possibly go wrong and what are the mitigations needed?

If these policies are incorrect and after the code is deployed its possible that it could overwrite the production media bucket or database if variables in the django projects settings are incorrect.

As long as the database are backed up  and buckets are version-ed we can restore the databases and/or  restore the media bucekt to a point in time using https://github.com/madisoft/s3-pit-restore

## Based on whats being changed are there any manual UAT or tests that should be run on the system after the deployment?

Verifying the sync users can access the sync buckets and the media buckets can be done before any code deploy and after the policy change.  After code is deployed running the sync scripts.

## Tasks
Include a checklist that both the person doing the deploy and another team member can do.  Also include these steps with any smoke tests in the tasks above. 

# Checklist
For example:
- [x] Fix name in ansible scripts for production and sync user policies
- [x] Add policy for staging sync user to write to staging's media bucket in ansible
- [x] Review and signoff of planned changes by @joduinn 
- [x] On production's media bucket turn on logging and versioning.
- [x] Install s3-pit-restore and have on hand.  This will make it easy to revert the Production media bucket if something goes wrong during the sync.
- [x] Delete the sync users and recreate with ansible(no rollback needed as these roles are not in use)
- [x] Confirm both Ansible created roles can write and read as expected from the sync bucket.
- [x] Confirm Stage sync role cannot write to Production media file(by sending dummy file).  This is important to prevent data loss or corruption later. Do not proceed without verifying Sync cannot disrupt Production.
- [x] Run aws sync from production to staging using staging's sync role
  - [x] Verify works and data is in the right bucket
- [ ]  Proceed with #1040 which handles importing data from staging bucket into the staging database.
- [ ] Review and signoff of deployed changes by @joduinn

**Comment by glassresistor** [comment]
@joduinn I've created a PR which contains all of the policies changes outlined here.  https://github.com/codeforamerica/intake-playbooks/pull/1  .  Please review and merge if it looks correct

**Comment by glassresistor** [comment]
Versioning is on after all so no need to backup the database and we can use s3-pit-restore

**Comment by glassresistor** [comment]
Setting up Logging requires creating another bucket to send the logs to.  It would also be helpful to connect those logs to CloudWatch and make sure permissions are properly tuned.  Given that I thought it best to do logging when setting up encryption on the bucket.

**Comment by glassresistor** [comment]
I've tested that these credentials works both with the aws cli directly and using the management commands in Django.

Handling the media buckets properties: logging, encryption, and versioning is in this ticket
https://github.com/codeforamerica/intake/issues/1112

@joduinn if you feel this is ready plus check this off and close
