### ISSUE TITLE
Final corrections for Alameda County

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#146]
- [x] Update address for sending RAP sheets to EBCLC to their office on 3130 Shattuck Ave, Berkeley, 94705
- [x] Change font of address on RAP sheet instructions
- [x] Update name of Alameda Public Defender to "Alameda County Public Defender's Office"
- [x] Replace link on APD partner page to http://www.acgov.org/defender/services/cleanslate.htm
- [x] Change questions "Do you have another phone number" to "What is another phone number we can reach you at?"
- [x] Adjust phone number field width and help text to imply that they should take a number
- [x] EBCLC phone number, last 4 digits should be 4064
- [x] RAP intro paragraph should say "to check what services you qualify for"
- [x] EBCLC fax: 510-849-1536 "Attention Clean Slate"
- [x] For RAP sheet directions, tell applicant they can mail, drop off, fax, or email their rap sheet.
- [x] Update RAP sheet instructions for CA applicants - remove #7 and #8 - #6 should say to contact CMR when they get their rap sheet so they can schedule a phone interview or clinic appointment
- [x] Update RAP sheet instructions for non CA applicants - #9 should say they can fax, email, or mail (remove drop off) RAP sheet - #10 should say they'll receive a message to set up a phone interview
- [x] Remove $25 fee waiver language from step #2 on RAP instructions
