### ISSUE TITLE
make working prototype for EBCLC intake

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#42]
Form field reference: https://docs.google.com/spreadsheets/d/1RwXX_ZXIq7jqXfllP2QBwXNfvpPAscOOylSl52gOfFk/edit#gid=70218205
- [x] Tie submissions to orgs based on eligibility #81
- [x] Ability for one org to refer to another #68
- [x] RAP sheet instructions page (content in multi-county copy doc) #70
- [x] Question about traffic & fees?

**Comment by bengolder** [comment]
![image](https://cloud.githubusercontent.com/assets/451510/18148689/0fde86bc-6f90-11e6-9ab0-5be0fa2e635e.png)
