### ISSUE TITLE
Rebuild app transfer between orgs. Mega task.  Waiting on #571, needs discussion.

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#451]
- [x] create ApplicationTransfer model based on StatusUpdate, along with "Transferred" StatusType #474

### The org user who is sending the transfer:

- [x] clicks on the transfer applicant button
- [x] they get a form which lets them:
	- [x] select which org to transfer to
	- [x] enter a reason (which will be sent to the receiving org)
	- [x] review and edit the notification that will be sent to the applicant
- on submission of the form:
	- [x] send a notification to the applicant #238
	- [x] tie a new event to the application that includes the "why" message
- [x] gets a flash message that the app has been transferred
- [x] Should see the app with a status type of "transferred" and should not be able to access it's details or history. #471 

### The receiving org user should:

- [x] see the new app in a bundle
- [x] it should be marked as a transfer
- [x] they should be able to see the transfer in the application history #374
- [x] they should be able to see previous status updates from the sending org in the app history #309

**Comment by bengolder** [comment]
@jazmynlatimer 
![screen shot 2017-02-27 at 11 22 03 am](https://cloud.githubusercontent.com/assets/451510/23375946/165a571e-fcdf-11e6-8956-ccf3481130e4.png)

**Comment by jazmynlatimer** [comment]
OMG amazing. yay - this is perfect.

One last thing - Lindsay and Vinuta requested that when an app is transferred, that we do not delete it from their App Index. Instead, keep it there with a note that it was transferred to the other org. They need to keep a record of that application, even if they aren't handling it anymore. 

Also, that Vinuta/EBCLC/the receiving org also should be notified when an app was transferred to them.

@bengolder is this feasible? They flagged this as a big usability issue.

**Comment by bengolder** [comment]
@jazmynlatimer that last request is actually pretty tricky. I'm not sure how long it would take, but it could be prohibitively big. In short we make certain assumptions about who can and should see which apps. If they can see the app, they are handling it. If they aren't handling it, they shouldn't see it. This is coded into how we handle permissions and logic at multiple levels.

**Comment by jazmynlatimer** [comment]
Hmm, darn. Ok, let's discuss this during our 1pm meeting. 

I get that those assumptions could be made and make sense to us, but our users don't think of it that way and have been confused about the "disappearing applications".

**Comment by jennifermarie** [comment]
Reviewing now, with context that there's a dependency on #571 and also that we should discuss in-person.
